"""Added group table

Revision ID: a2cf4de47f92
Revises: af1a150d0ff2
Create Date: 2019-11-05 17:25:29.194905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2cf4de47f92'
down_revision = 'af1a150d0ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.CheckConstraint('length(name) > 0', name=op.f('ck_group_group_name_len_gt_0')),
    sa.CheckConstraint('lower(name) = name', name=op.f('ck_group_group_name_is_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group')),
    sa.UniqueConstraint('name', name=op.f('uq_group_name')),
    schema='core'
    )
    # op.create_table('user',
    # sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    # sa.Column('login', sa.String(), nullable=False),
    # sa.Column('password', sa.String(), nullable=False),
    # sa.CheckConstraint('length(login) > 0', name=op.f('ck_user_login_len_gt_0')),
    # sa.CheckConstraint('length(password) > 0', name=op.f('ck_user_password_len_gt_0')),
    # sa.CheckConstraint('lower(login) = login', name=op.f('ck_user_login_is_lowercase')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    # schema='core'
    # )
    op.create_table('user_group',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['core.group.id'], name=op.f('fk_user_group_group_id_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.user.id'], name=op.f('fk_user_group_user_id_user'), ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'group_id', name=op.f('uq_user_group_user_id')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group', schema='core')
    # op.drop_table('user', schema='core')
    op.drop_table('group', schema='core')
    # ### end Alembic commands ###
